#!/bin/sh
#
# Setup a build env and build gdb similar to how ports builds it

usage()
{
	cat <<EOF
usage: build [-g gcc|-G] [-r sysroot] [-s gdbdir] -f config file
       build [-g gcc|-G] [-r sysroot] [-s gdbdir] [config]

       -f: path to a config file
       -g: gcc compiler to use
       -G: pick a default GCC for the config
       -r: path to a sysroot (defaults to / for native)
       -s: path to GDB source (defaults to pwd)
       config: built in configuration, native if none given
EOF
	exit 1
}

GDB_DIR=${PWD}
while getopts "f:Gg:r:s" option; do
	case "$option" in
		f)
			config="$OPTARG"
			;;
		G)
			USE_GCC=yes
			;;
		g)
			WITH_GCC="$OPTARG"
			;;
		r)
			ROOTFS="$OPTARG"
			;;
		s)
			GDB_DIR="$OPTARG"
			;;
		*)
			usage
			;;
	esac
done
shift $((OPTIND - 1))

# Check for invalid arguments
if [ $# -gt 1 ]; then
	usage
fi

if [ $# -eq 1 -a -n "$config" ]; then
	usage
fi

if [ -n "$USE_GCC" -a -n "$WITH_GCC" ]; then
	usage
fi
	
# Figure out some variables and set some defaults
version=`uname -r | cut -d- -f1`
arch=`uname -m`
case $arch in
	amd64)
		cfgarch=x86_64
		;;
	*)
		cfgarch=${arch}
		;;
esac

# Cross-compile configurations should set this to the triple
# to pass to --host
HOST=

CONFIGURE_ARGS=
CONFIGURE_ENV=
LDFLAGS=
PYTHON=

if [ -n "${WITH_GCC}" ]; then
	CC="${WITH_GCC}"
	CXX=$(echo ${WITH_GCC} | sed -e 's/gcc/g++/')
else
	CC="cc"
	CXX="c++"
fi

if [ -n "$config" ]; then
	if ! [ -r "$config" ]; then
		echo "Can't read config file"
		exit 1
	fi
	. ${config}
	config=
elif [ $# -eq 1 ]; then
	case "$1" in
		mips)
			obj=obj.mips
			: ${ROOTFS:="/home/john/work/qemu/mips/rootfs"}
			HOST=mips-freebsd
			CLANG_TARGET=mips-freebsd13.0
			CC_FLAGS="-msoft-float -mabi=32"
			if [ -n ${USE_GCC} ]; then
				CC="mips-unknown-freebsd${version}-gcc"
				CXX="mips-unknown-freebsd${version}-g++"
				AR=/usr/bin/ar
			fi
			;;
		mipsn32)
			obj=obj.mipsn32
			: ${ROOTFS:="/home/john/work/qemu/mipsn32/rootfs"}
			HOST=mips64-freebsd
			CLANG_TARGET=mips-freebsd13.0-xxx
			CC_FLAGS="-msoft-float -mabi=n32"
			if [ -n ${USE_GCC} ]; then
				CC="mips-unknown-freebsd${version}-gcc"
				CXX="mips-unknown-freebsd${version}-g++"
			fi
			;;
		mips64)
			obj=obj.mips64
			: ${ROOTFS:="/home/john/work/qemu/mips64/rootfs"}
			HOST=mips64-freebsd
			CLANG_TARGET=mips64-freebsd13.0
			CC_FLAGS="-msoft-float -mabi=64"
			if [ -n ${USE_GCC} ]; then
				CC="mips-unknown-freebsd${version}-gcc"
				CXX="mips-unknown-freebsd${version}-g++"
				AR=/usr/bin/ar
			fi
			;;
		cheri256)
			obj=obj.cheri
			: ${ROOTFS:="/home/john/work/cheri/mips/rootfs"}
			HOST=mips64-freebsd
			CLANG_TARGET=cheri-freebsd13.0
			# -march=mips4?
			CC_FLAGS="-msoft-float -mstack-alignment=32 \
-cheri=256 -mabi=64 -B /usr/local/mips-freebsd/bin"
			CC="/usr/cheri/bin/clang"
			CXX="/usr/cheri/bin/clang++"
			AR=/usr/bin/ar
			;;
		cheri128)
			obj=obj.cheri128
			: ${ROOTFS:="/home/john/work/cheri/mips/rootfs128"}
			HOST=mips64-freebsd
			CLANG_TARGET=cheri-freebsd13.0
			# -march=mips4?
			CC_FLAGS="-msoft-float -mstack-alignment=16 \
-cheri=128 -mabi=64 -B /usr/local/mips-freebsd/bin"
			CC="/usr/cheri/bin/clang"
			CXX="/usr/cheri/bin/clang++"
			AR=/usr/bin/ar
			;;
		mips64c)
			obj=obj.cheriabi128
			: ${ROOTFS:="/home/john/work/cheri/mips/rootfs128"}
			HOST=mips64-freebsd
			CLANG_TARGET=cheri-freebsd13.0
			CC_FLAGS="-msoft-float -mstack-alignment=16 \
-cheri=128 -mabi=purecap -cheri-cap-table-abi=pcrel -mxcaptable \
-B /usr/local/mips-freebsd/bin"
			CC="/usr/cheri/bin/clang"
			CXX="/usr/cheri/bin/clang++"
			AR=/usr/bin/ar
			;;
		aarch64)
			obj=obj.aarch64
			: ${ROOTFS:="/mnt"}
			HOST=aarch64-freebsd
			CLANG_TARGET=aarch64-freebsd13.0
			AR=/usr/bin/ar
			;;
		armv7)
			obj=obj.arm
			: ${ROOTFS:="/mnt"}
			HOST=arm-gnueabi-freebsd
			CLANG_TARGET=armv7-gnueabihf-freebsd13.0
			AR=/usr/bin/ar
			;;
		riscv64)
			obj=obj.riscv64
			: ${ROOTFS:="/home/john/work/qemu/riscv64/rootfs"}
			HOST=riscv64-freebsd
			CLANG_TARGET=riscv64-freebsd13.0
			CC_FLAGS="-march=rv64imafdc -mabi=lp64d"
			CLANG_CC_FLAGS="-mno-relax"
			if [ -n ${USE_GCC} ]; then
				CC="riscv64-unknown-freebsd${version}-gcc"
				CXX="riscv64-unknown-freebsd${version}-g++"
			fi
			AR="riscv64-unknown-freebsd${version}-ar"
			;;
		powerpc64)
			obj=obj.powerpc64
			: ${ROOTFS:="/qemu/ppc64/rootfs"}
			HOST=powerpc64-freebsd
			CLANG_TARGET=powerpc64-freebsd13.0
			if [ -n ${USE_GCC} ]; then
				CC="powerpc64-unknown-freebsd${version}-gcc"
				CXX="powerpc64-unknown-freebsd${version}-g++"
			fi
			;;
		*)
			echo "Unknown configuration"
			exit 1
			;;
	esac
else
	case $arch in
		amd64)
			obj=obj
			;;
		*)
			obj=obj.${arch}
			;;
	esac
	if [ -n "$WITH_GCC" ]; then
		obj=${obj}.gcc
		WANT_WERROR=yes
	fi
	if [ -n "$USE_GCC" ]; then
		echo "native doesn't support implicit gcc via -G"
		exit 1
	fi

	if [ -x /usr/local/bin/python -a -z "${WITHOUT_PYTHON}" ]; then
		PYTHON="/usr/local/bin/python"
	fi
fi

cc_version=`${CC} -v 2>&1`
if [ $? -ne 0 ]; then
	echo "Compilers are not executable:"
	echo " CC=${CC}"
	echo " CXX=${CXX}"
	exit 1
fi

if echo "${cc_version}" | grep -q clang ; then
	# clang-specific warnings to disable
	EXTRA_CFLAGS="-Wno-absolute-value -Wno-parentheses-equality"
	EXTRA_CFLAGS="${EXTRA_CFLAGS} -Wno-unknown-warning-option"

	if [ -n "${CLANG_TARGET}" ]; then
		CC_FLAGS="-target ${CLANG_TARGET} ${CC_FLAGS}"
	fi
	CC_FLAGS="${CC_FLAGS} ${CLANG_CC_FLAGS}"
	: ${LDFLAGS:="-fuse-ld=lld -Wl,--gdb-index"}
fi
if [ -n "${ROOTFS}" ]; then
	CC_FLAGS="${CC_FLAGS} --sysroot=${ROOTFS}"
fi
CC="${CC} ${CC_FLAGS}"
CXX="${CXX} ${CC_FLAGS}"

if [ -n "${AR}" ]; then
    CONFIGURE_ENV="${CONFIGURE_ENV} AR=${AR}"
fi

if [ -n "${WITH_UBSAN}" ]; then
	CONFIGURE_ARGS="${CONFIGURE_ARGS} --enable-ubsan"
else
	CONFIGURE_ARGS="${CONFIGURE_ARGS} --disable-ubsan"
fi

if [ -n "${PYTHON}" ]; then
	CONFIGURE_ARGS="${CONFIGURE_ARGS} --with-python=${PYTHON}"
else
	CONFIGURE_ARGS="${CONFIGURE_ARGS} --without-python"	
fi

if [ -n "${HOST}" ]; then
	CONFIGURE_ARGS="${CONFIGURE_ARGS} --without-expat"
	CONFIGURE_ARGS="${CONFIGURE_ARGS} --disable-source-highlight"
	CONFIGURE_ENV="${CONFIGURE_ENV} gl_cv_func_gettimeofday_clobber=no"
else
	CONFIGURE_ARGS="${CONFIGURE_ARGS} --with-expat"
fi

if [ -z "${WANT_WERROR}" ]; then
	CONFIGURE_ARGS="${CONFIGURE_ARGS} --disable-werror"
fi
	
# First, make an obj tree
mkdir $obj

# Next, run configure
CONFIGURE_ARGS="--enable-targets=all \
--with-separate-debug-dir=/usr/lib/debug \
--without-libunwind-ia64 --enable-tui \
--prefix=/usr/local  --mandir=/usr/local/man --infodir=/usr/local/info/ \
--build=${cfgarch}-portbld-freebsd${version} --disable-nls \
--disable-ld --enable-64-bit-bfd ${CONFIGURE_ARGS}"

if [ -n "${HOST}" ]; then
	CONFIGURE_ARGS="${CONFIGURE_ARGS} --host=${HOST}"
fi

(cd $obj;
 env CC_FOR_BUILD="cc" CC="${CC}" CPP="cpp" CXX="${CXX}" \
     CFLAGS="-pipe  -DRL_NO_COMPAT -Wno-unused-function -Wno-unused-variable ${EXTRA_CFLAGS} -g -O2 -DLIBICONV_PLUG -g -fno-strict-aliasing" \
     CPPFLAGS="-DLIBICONV_PLUG -I/usr/local/include" \
     CXXFLAGS="-pipe -DRL_NO_COMPAT -Wno-unused-function -Wno-unused-variable ${EXTRA_CFLAGS} -g -O2 -DLIBICONV_PLUG -g -fno-strict-aliasing" \
     LDFLAGS="${LDFLAGS} -L/usr/local/lib" LIBS="" \
     INSTALL="/usr/bin/install -c " \
     INSTALL_DATA="install   -m 0644" \
     INSTALL_LIB="install    -m 444" \
     INSTALL_PROGRAM="install    -m 555" \
     INSTALL_SCRIPT="install   -m 555" \
     CONFIGURED_M4=m4 CONFIGURED_BISON=byacc TMPDIR="/tmp" MAKE=gmake \
     PYTHON="${PYTHON}" SHELL=/bin/sh CONFIG_SHELL=/bin/sh \
     CONFIG_SITE=/usr/ports/Templates/config.site \
     lt_cv_sys_max_cmd_len=262144 ${CONFIGURE_ENV} \
     ${GDB_DIR}/configure ${CONFIGURE_ARGS} )
